#!/usr/bin/python3 

import glob
import re
import io
import sys
import csv
import os

if len(sys.argv) < 2:
    print("designate bodytext")
    exit(1)

fbody = sys.argv[1]

files = glob.glob("*.pdf")

userlist = []
for file in files:
    user = re.search(r'^[SM][0-9]+', file)
    newfile = user.group(0) + "_" + fbody + ".pdf"
    os.rename(file, newfile)
    if user.group(0).startswith("S"):
        userid = re.sub(r"^S", "us", user.group(0))
    elif user.group(0).startswith("M"):
        userid = re.sub(r"^M", "dm", user.group(0))
    else:
        exit("user id does not start with S|M")
    userlist.append([userid, 0, newfile, file])

with open("upload.csv", "w", encoding="cp932") as dest:
    writer = csv.writer(dest)
    for userrow in sorted(userlist):
        writer.writerow(userrow)

